name: 问题反馈
description: 反馈出现的问题
title: '[BUG]: '
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ##  提交问题前请先注意以下事项

        + 注意：在「[B 站上线 IP 属地功能](https://www.bilibili.com/read/cv17590180)」前发布的评论不会显示。
        + 部分场景可能未适配。请检查[是否支持](#目前支持的场景)该场景，并确认脚本已在当前页面激活。
        + 请确保脚本为最新版本且运行正常。可尝试关闭其他可能冲突的脚本来排查问题。
        + **仅提供简单反馈「无效」时，我们往往难以定位问题。建议尽量补充更多信息，方便我们复现和修复。若条件允许，可以打开开发者工具并重新加载页面，查看控制台（Console）中是否有与 BiliReveal / userscript 相关的报错信息。**
  - type: checkboxes
    id: developer_mode
    attributes:
      label: 请确认您已满足以下条件：
      options:
        - label: 我已开启浏览器的 [开发者模式、允许用户脚本](https://www.tampermonkey.net/faq.php?locale=zh#Q208)
          required: true
  - type: input
    id: version
    attributes:
      label: 脚本版本
      placeholder: 1.6.1
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: 浏览器
      placeholder: Chrome
    validations:
      required: true
  - type: input
    id: userscript-manager
    attributes:
      label: 用户脚本管理器
      placeholder: Tampermonkey, Greasemonkey, Stay
      value: Tampermonkey
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: 出现问题的网址
      description: 提供出现问题的网页链接
      placeholder: https://bilibili.com/....
    validations:
      required: true
  - type: input
    id: description
    attributes:
      label: 描述现象
      description: 简短描述出现的问题现象
      placeholder: 请输入问题的简短描述
    validations:
      required: true
  - type: textarea
    id: reproduction_steps
    attributes:
      label: 如何复现
      description: 如果需要一定的操作步骤才能复现问题，请在此处描述。
      placeholder: |-
        1. 进入 '...' 网址
        2. 点击 '....'
