name: 问题反馈
description: 反馈出现的问题
title: '[BUG]: '
labels: ["bug"]
body:
  - type: checkboxes
    id: precheck
    attributes:
      label: 我的问题已经排除以下情况：
      options:
        - label: 已开启浏览器的 [开发者模式、允许用户脚本](https://www.tampermonkey.net/faq.php?locale=zh#Q208)，且脚本在当前页面正常生效
          required: true
        - label: 「[B 站上线 IP 属地功能](https://www.bilibili.com/read/cv17590180)」之前发布的评论本身不会显示属地
          required: true
        - label: 当前页面属于[已支持的场景](https://github.com/maxchang3/BiliReveal#%E7%9B%AE%E5%89%8D%E6%94%AF%E6%8C%81%E7%9A%84%E5%9C%BA%E6%99%AF) (对于不支持的场景，请提交功能请求而非 BUG 反馈)
          required: true
        - label: 已更新到最新版本，并排查过其他脚本冲突
          required: true
  - type: input
    id: version
    attributes:
      label: 脚本版本
      placeholder: 1.6.1
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: 浏览器
      placeholder: Chrome
    validations:
      required: true
  - type: input
    id: userscript-manager
    attributes:
      label: 用户脚本管理器
      placeholder: Tampermonkey, Greasemonkey, Stay
      value: Tampermonkey
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: 出现问题的网址
      description: 提供出现问题的网页链接
      placeholder: https://bilibili.com/....
    validations:
      required: true
  - type: input
    id: description
    attributes:
      label: 描述现象
      description: 简短描述出现的问题现象
      placeholder: 请输入问题的简短描述
    validations:
      required: true
  - type: textarea
    id: reproduction_steps
    attributes:
      label: 如何复现
      description: 如果需要一定的操作步骤才能复现问题，请在此处描述。
      placeholder: |-
        1. 进入 '...' 网址
        2. 点击 '....'
  - type: textarea
    id: console_output
    attributes:
      label: Console 报错信息（可选）
      description: 如有能力，请查看开发者工具 Console，确认是否存在 BiliReveal / userscript 报错，并分享相关信息或截图
      placeholder: 请在此粘贴报错信息或截图描述
